### ISSUE TITLE
failed to fuse image

### ISSUE THREAD

**Issue by jediofgever** [ros-industrial/yak_ros2#10]
HI , 
I am trying to get a mesh created with gazebo simulated  realsense depth camera. 

I have attached camera to a robot with base_link. The TF tree from map->base_link->camera_link is  complete and faultless. 

The callback that does fusion is being called. But the fusion cannot be performed for some reason. I am also sure that I have remapped the camera topic and inputted correct intrinsic params. I also enabled ICP because I have no FK, my camera is attached to a mobile robot. And the transform is provided by gazebo link publisher. 

I can see the window populate with some blinks but no fusion is being done. 

![Screenshot from 2021-01-07 22-15-30](https://user-images.githubusercontent.com/18460336/103902761-f1fdf100-5135-11eb-8729-35dfe23058c0.png)

Right after aove image it goes blank as below, and this keeps going on

![Screenshot from 2021-01-07 22-15-32](https://user-images.githubusercontent.com/18460336/103902767-f3c7b480-5135-11eb-90cb-7aff36f510ce.png)

and I tink since fusion cannot bedone the pose is being reset. 

I see a cycle of this output i terminal. 

```
[yak_ros2_node-1] Resetting to: [1, 0, 0, 0;
[yak_ros2_node-1]  0, 1, 0, 0;
[yak_ros2_node-1]  0, 0, 1, 0;
[yak_ros2_node-1]  0, 0, 0, 1]
[yak_ros2_node-1] [WARN] [1610028934.863269958] [yak_ros2_node]: Failed to fuse image
[yak_ros2_node-1] [INFO] [1610028934.863677227] [yak_ros2_node]: Got depth image
[yak_ros2_node-1] [WARN] [1610028934.915731306] [yak_ros2_node]: Failed to fuse image
[yak_ros2_node-1] [INFO] [1610028934.916144321] [yak_ros2_node]: Got depth image
[yak_ros2_node-1] [INFO] [1610028935.124561495] [yak_ros2_node]: Got depth image
[yak_ros2_node-1] Reset Volume
[yak_ros2_node-1] Reset Pose
[yak_ros2_node-1] Resetting to: [1, 0, 0, 0;
[yak_ros2_node-1]  0, 1, 0, 0;
[yak_ros2_node-1]  0, 0, 1, 0;
[yak_ros2_node-1]  0, 0, 0, 1]
```

Since no fusion o no pointcloud. When I trigger service to save, the point cloud is empty.  Can you please elaborate what could be reason of unsuccessful fusion ?

**Comment by schornakj** [comment]
> I have attached camera to a robot with base_link. The TF tree from map->base_link->camera_link is complete and faultless.
> 
> The callback that does fusion is being called. But the fusion cannot be performed for some reason. I am also sure that I have remapped the camera topic and inputted correct intrinsic params. I also enabled ICP because I have no FK, my camera is attached to a mobile robot. And the transform is provided by gazebo link publisher.

I think is technically an issue with the base Yak package rather than yak_ros2 specifically, but it's OK to ask those kinds of questions here.

I believe in this case you would actually want to disable ICP. Even though you don't have forward kinematics from a robot arm, it sounds like you're providing the transform from the `map` frame to the `base_link` frame using the Gazebo link publisher (correct me if I'm wrong about this). This has the same end result of providing an accurate calculation of the position of the camera in the global environment as doing forward kinematics would for a robot arm.

Also, most of the recent use of these packages has focused on the forward kinematics use case, so I expect that ICP probably does not work correctly in the full image integration pipeline. It's probably not a huge amount of work to implement it again, but it does require someone with some free time to sit down and actually do it.

For reference, the failure that causes the volume and pose to be reset happens [here](https://github.com/ros-industrial/yak/blob/2922b91b61b74fa3c3d7c7a718b8a0e7bb297942/yak/src/kfusion/kinfu.cpp#L228-L252), probably when `estimateTransform` returns `False`.
